name: 'Basic Reporting'
description: 'Generates basic reports for companies plus wrapping README.md files in the repository'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node20'
  main: 'index.js'